remotes:
- git@github.com:nyarly/commute.git
- git@github.com:nyarly/cygnus.git
- git@github.com:nyarly/engulf.git
- git@github.com:nyarly/inlinefiles.git
- git@github.com:nyarly/install_releases.git
- git@github.com:nyarly/jobmake.git
- git@github.com:nyarly/legendary.git
- git@github.com:nyarly/mergetron.git
- git@github.com:nyarly/palomino.git
- git@github.com:nyarly/rust-cryptopals.git
- git@github.com:nyarly/sous.git
- git@github.com:opentable/go-singularity
- git@github.com:opentable/otpl-sous-converter.git
- git@github.com:opentable/sous-build-containers.git
- git@github.com:opentable/sous-demo.git
- git@github.com:nyarly/tmux-pi.git
- git@github.com:nyarly/nixos.git
- git@github.com:NixOS/nixpkgs
- git@github.com:nyarly/dotfiles.git
- git@github.com:opentable/ot-sous-server.git
- git@github.com:opentable/swaggering
- git@github.com:opentable/homebrew-public.git
- git@github.com:opentable/sous-teamcity-integration.git
- git@github.com:opentable/teamcity-cli
- git@github.com:nyarly/ergo.git
- git@github.com:nyarly/roadforest.git
- git@github.com:nyarly/hawser.git
- git@github.com:nyarly/mattock.git
- git@github.com:joshroby/pockyclocks.git
- git@github.com:nyarly/diecut.git
- git@github.com:nyarly/taxo.git
- git@github.com:nyarly/edict.git
- git@github.com:nyarly/bibliotech.git
- git@github.com:nyarly/calibrate.git
- git@github.com:nyarly/janice.git
- git@github.com:nyarly/helm.git
- git@github.com:nyarly/blog.git
- git@github.com:go-kit/kit
- git@github.com:nyarly/quickfixable.git
- git@github.com:opentable/ot-go-lib
- git@github.com:nyarly/spies
- git@github.com:nyarly/versiontool.git
- git@github.com:opentable/go-discovery-client-rig.git
- git@github.com:nyarly/socket-notify.git
- git@github.com:nyarly/d2tools.git
- git@github.com:LRDesign/TimePulse-homepage.git
- git@github.com:nyarly/personal-servers.git
- git@github.com:opentable/sous-database-migration.git
- git@github.com:opentable/github-teamcity-repeater.git
- git@github.com:nyarly/cycle-sjw.git
- git@github.com:opentable/ot-eda-golang.git
- git@github.com:iovisor/bcc.git
- git@github.com:nyarly/quickfixable-rs.git
- git@github.com:gotham-rs/gotham.git
- git@github.com:opentable/mezzo.git
