remotes:
- git@github.com:nyarly/commute.git
- git@github.com:nyarly/sous.git
- git@github.com:nyarly/legendary.git
- git@github.com:nyarly/engulf
- git@git.lrdesign.com:judson/blog.git
- git@github.com:nyarly/jobmake.git
