#!/usr/bin/env bash

if [[ $# < 1 ]]; then
  echo "Usage: $0 <repo>"
  echo "<repo> is required"
  exit 1
fi

repo=$1

cd $(dirname $0)
dotfiles=$(git rev-parse --show-toplevel)

vcsh list | grep -q "^${repo}$"
if [ $? -ne 0 ]; then
  echo "VCSH doesn't maintain a repo for $repo"
  exit 3
fi

BRANCH_EXISTS=yes
git branch --list "$repo" | grep -q "^\s*${repo}$"
if [ $? -ne 0 ]; then
  echo "No branch exists for $repo"
  BRANCH_EXISTS=no
  git branch "$repo"

  git read-tree --prefix="$repo"/ -u "$repo"
fi

vcsh $repo remote -v
vcsh $repo config --get-regexp branch.master
vcsh $repo config --get-regexp remote.origin

set -eu

vcsh $repo config --replace-all branch.master.merge "refs/heads/${repo}"
vcsh $repo config --replace-all push.default nothing
vcsh $repo config --replace-all remote.origin.fetch +refs/heads/${repo}:refs/remotes/origin/${repo}
vcsh $repo config --replace-all remote.origin.push "${repo}:${repo}"
vcsh $repo remote set-url origin "file://${dotfiles}"
vcsh $repo checkout -b $repo || true

echo "***"
vcsh $repo remote -v
vcsh $repo config --get-regexp branch.master
vcsh $repo config --get-regexp remote.origin
