#!/usr/bin/env bash

if [[ $# < 1 ]]; then
  echo "Usage: $0 <repo>"
  echo "<repo> is required"
  exit 1
fi

repo=$1

cd $(dirname $0)
dotfiles=$(git rev-parse --show-toplevel)

if git branch --list "$repo" | grep -qv "^\s*${repo}$"; then
  echo "No branch exists for $repo"
  exit 2
fi

vcsh list | grep -q "^${repo}$"
if [ $? -ne 0 ]; then
  echo "VCSH doesn't maintain a repo for $repo"
  exit 3
fi

vcsh $repo remote -v
vcsh $repo config --get-regexp branch.master
vcsh $repo config --get-regexp remote.origin

set -eu

vcsh $repo config --replace-all branch.master.merge "refs/heads/${repo}"
vcsh $repo config --replace-all push.default nothing
vcsh $repo config --replace-all remote.origin.fetch +refs/heads/master:refs/remotes/origin/${repo}
vcsh $repo config --replace-all remote.origin.push "master:${repo}"
vcsh $repo remote set-url origin "file://${dotfiles}"

echo "***"
vcsh $repo remote -v
vcsh $repo config --get-regexp branch.master
vcsh $repo config --get-regexp remote.origin
