#!/bin/sh
mkdir .git/tags_lock 2>/dev/null || exit 0
set -e
PATH="/usr/local/bin:$PATH"
trap "rmdir .git/tags_lock; rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql
mv .git/tags.$$ .git/tags 
